### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy.

### ISSUE THREAD

**Issue by lucassKim** [psywaves/EVCF#1]
thank you for share your nice algorithm and code
occurred error at evaluation.py line 94
 TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

#should be removed if not necessary
   pred_val = np.array(pred_val)

tried remove code as it mentioned but it occurred again at other rows

**Comment by lucassKim** [comment]
pred_val = pred_val.cpu().numpy()
            x = x.cpu().numpy()

but not sure this is best

**Comment by YooSungHyun** [comment]
your eval metric is good?
i get this value so low....
- BEST VALIDATION NDCG: 0.03890 (150 epochs) -
NDCG@100: 0.03991(0.0006)  |  Loss: 62.22
NDCG@20: 0.03042(0.0005)   |  RE: 61.69
NDCG@10: 0.03053(0.0005)   |  KL: 0.53
Recall@50: 0.04612(0.0007) |  Recall@5: 0.03093(0.0006)
Recall@20: 0.03353(0.0006) |  Recall@1: 0.03752(0.0010)
Recall@10: 0.03031(0.0005)
